apiVersion: v1
kind: Service
metadata:
  name: opengrok
  namespace: opengrok
  labels:
    app: opengrok
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30001
    protocol: TCP
  - name: ssh
    port: 22
    nodePort: 30002
    protocol: TCP
  selector:
    app: opengrok
